/*
 *  UCF COP3330 Summer 2021 Assignment 3 Solution
 *  Copyright 2021 John Peachey
 */

@startuml
'https://plantuml.com/class-diagram


ProductCentral o-- Product
App o-- ProductCentral


class App {

    userInput()
}

class ProductCentral{
    createProductList()
    findProduct()
    productInfo()
}

class Product {
    String name
    double price
    int quantity

    product()
}

@enduml